phone_dimension=71; //distance top to bottom of phone in landscape position
case_width=140;
case_height=80;
case_radius=5; //used for the outside corners
case_thickness=5;
opening_height=56;
opening_diameter=97; //used for left and right side of the "television screen" opening
border_width=2;
border_height=1;
border_inset=5;
button1_diameter=8;
button1_height=0.5;
button1_x=60;
button1_y=30;
button2_diameter=4;
button2_height=0.5;
button2_x=60;
button2_y=-20;
button3_diameter=4;
button3_height=0.5;
button3_x=60;
button3_y=-30;
foot_height=10;
foot_width=5;
foot_depth=20;
rubber_band_post_height=5;
rubber_band_post_angle=30;
antenna_diameter=40;
antenna_wire=2;
antenna_ball_diameter=4;
$fn=50;

difference(){
hull(){
translate([-case_width/2,-case_height/2,0])
cylinder(r=case_radius,h=case_thickness);
translate([-case_width/2,case_height/2,0])
cylinder(r=case_radius,h=case_thickness);
translate([case_width/2,-case_height/2,0])
cylinder(r=case_radius,h=case_thickness);
translate([case_width/2,case_height/2,0])
cylinder(r=case_radius,h=case_thickness);
}
intersection(){
translate([-opening_diameter/2,-opening_height/2,0])
cube([opening_diameter,opening_height,case_thickness]);
cylinder(d=opening_diameter,h=case_thickness);
}
difference(){
hull(){
translate([-case_width/2+border_inset,-case_height/2+border_inset,0])
cylinder(r=case_radius,h=border_height);
translate([-case_width/2+border_inset,case_height/2-border_inset,0])
cylinder(r=case_radius,h=border_height);
translate([case_width/2-border_inset,-case_height/2+border_inset,0])
cylinder(r=case_radius,h=border_height);
translate([case_width/2-border_inset,case_height/2-border_inset,0])
cylinder(r=case_radius,h=border_height);
}
hull(){
translate([-case_width/2+border_inset+border_width,-case_height/2+border_inset+border_width,0])
cylinder(r=case_radius,h=border_height);
translate([-case_width/2+border_inset+border_width,case_height/2-border_inset-border_width,0])
cylinder(r=case_radius,h=border_height);
translate([case_width/2-border_inset-border_width,-case_height/2+border_inset+border_width,0])
cylinder(r=case_radius,h=border_height);
translate([case_width/2-border_inset-border_width,case_height/2-border_inset-border_width,0])
cylinder(r=case_radius,h=border_height);
}
}
translate([button1_x,button1_y,0])
cylinder(d=button1_diameter,h=button1_height);
translate([button2_x,button2_y,0])
cylinder(d=button2_diameter,h=button2_height);
translate([button3_x,button3_y,0])
cylinder(d=button3_diameter,h=button3_height);
}

difference(){
union(){
translate([-(case_width-case_radius)/2,-(case_height-case_radius)/2,case_thickness])
cube([case_width-case_radius,case_height-case_radius,case_thickness]);
rubber_band_posts();
}
translate([-(case_width-case_radius)/2,-phone_dimension/2,case_thickness])
cube([case_width-case_radius,phone_dimension,case_thickness]);
translate([-500,-500,case_thickness*2])
cube([1000,1000,20]);
}


module rubber_band_posts(){
translate([-(case_width-case_radius)/2,-(case_height-case_radius)/2,case_thickness])
rotate([rubber_band_post_angle,0,0])
cube([rubber_band_post_height,rubber_band_post_height,rubber_band_post_height]);
translate([(case_width-case_radius)/2-rubber_band_post_height,-(case_height-case_radius)/2,case_thickness])
rotate([rubber_band_post_angle,0,0])
cube([rubber_band_post_height,rubber_band_post_height,rubber_band_post_height]);
translate([(case_width-case_radius)/2-rubber_band_post_height,(case_height-case_radius)/2,case_thickness])
rotate([90-rubber_band_post_angle,0,0])
cube([rubber_band_post_height,rubber_band_post_height,rubber_band_post_height]);
translate([-(case_width-case_radius)/2,(case_height-case_radius)/2,case_thickness])
rotate([90-rubber_band_post_angle,0,0])
cube([rubber_band_post_height,rubber_band_post_height,rubber_band_post_height]);
}

module antenna(){
difference(){
cylinder(d=antenna_diameter,h=case_thickness);
translate([-antenna_diameter/2,-antenna_diameter/2,0])
cube([antenna_diameter,antenna_diameter/2,case_thickness]);
}
rotate([0,0,-45]){
translate([0,2,0])
cube([antenna_wire,antenna_diameter,case_thickness]);
translate([antenna_wire/2,antenna_diameter,0])
cylinder(d=antenna_ball_diameter,h=case_thickness);
}
rotate([0,0,45]){
translate([0,2,0])
cube([antenna_wire,antenna_diameter,case_thickness]);
translate([antenna_wire/2,antenna_diameter,0])
cylinder(d=antenna_ball_diameter,h=case_thickness);
}
}

translate([0,-case_height/2,0])
rotate([0,0,180])
antenna();
