$fn=100;

THICKNESS=3;
WIDTH=15;
BACKDEPTH=20;
FRONTDEPTH=15;
MIDLENGTH=80;
BACKLENGTH=40;
FRONTLENGTH=25;

cube([MIDLENGTH,THICKNESS,WIDTH]);
translate([0,BACKDEPTH,0]) cube([BACKLENGTH,THICKNESS,WIDTH]);
cube([THICKNESS,BACKDEPTH,WIDTH]);
translate([MIDLENGTH-THICKNESS,-FRONTDEPTH,0]) cube([THICKNESS,FRONTDEPTH,WIDTH]);
translate([MIDLENGTH-FRONTLENGTH+(WIDTH/2),-FRONTDEPTH-THICKNESS,0]) cube([FRONTLENGTH-(WIDTH/2),THICKNESS,WIDTH]);
translate([MIDLENGTH-FRONTLENGTH+(WIDTH/2),-FRONTDEPTH,WIDTH/2]) rotate([90,0,0]) cylinder(d=WIDTH,h=THICKNESS);
translate([BACKLENGTH,BACKDEPTH+THICKNESS,WIDTH/2]) rotate([90,0,0]) cylinder(d=WIDTH,h=THICKNESS);