// preview[view:south,tiLt:top]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[General]*/
//**NOTICE ALL MESUREMENTS ARE IN MILLIMETERS**
//Lower Is Faster To Load, Higher Is Better To Print.
render_quality=10;//[10:60]
//Pushes all rings down to the print bed
flaten_to_bed="yes";//[no:yes]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Attachment Loop Control]*/
thickness_of_loop=1;
stretch_amount_for_loop=1.5;
front_edge_width_of_loop=4;
front_to_back_of_loop=3;
orientation_of_loop="vertical";//[horizontal,vertical]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Rings]*/
number_of_outer_rings=1;//[1,2,3,4,5,6,7,8,9,10,11,12]
inner_rings_rotate_with_outer_ring_1="no";//[no,yes]
thickness_of_outer_ring_1=2;//[1:20]
radius_of_outer_ring_1=18;//[1:100]
y_shift_of_outer_ring_1=0;//[-100:100]
symmetries_of_outer_ring_1=1;//[1:36]
//Do Not Touch. Be Forewarned This WILL Misalign The Loop
twist_percent_for_outer_ring_1=0;
inner_rings_rotate_with_outer_ring_2="no";//[no,yes]
thickness_of_outer_ring_2=2;//[1:20]
radius_of_outer_ring_2=18;//[1:100]
y_shift_of_outer_ring_2=0;//[[-100:100]
symmetries_of_outer_ring_2=1;//[1:36]
twist_percent_for_outer_ring_2=0;
inner_rings_rotate_with_outer_ring_3="no";//[no,yes]
thickness_of_outer_ring_3=2;//[1:20]
radius_of_outer_ring_3=18;//[1:100]
y_shift_of_outer_ring_3=0;//[-100:100]
symmetries_of_outer_ring_3=1;//[1:36]
twist_percent_for_outer_ring_3=0;
inner_rings_rotate_with_outer_ring_4="no";//[no,yes]
thickness_of_outer_ring_4=2;//[1:20]
radius_of_outer_ring_4=18;//[1:100]
y_shift_of_outer_ring_4=0;//[-100:100]
symmetries_of_outer_ring_4=1;//[1:36]
twist_percent_for_outer_ring_4=0;
inner_rings_rotate_with_outer_ring_5="no";//[no,yes]
thickness_of_outer_ring_5=2;//[1:20]
radius_of_outer_ring_5=18;//[1:100]
y_shift_of_outer_ring_5=0;//[-100:100]
symmetries_of_outer_ring_5=1;//[1:36]
twist_percent_for_outer_ring_5=0;
inner_rings_rotate_with_outer_ring_6="no";//[no,yes]
thickness_of_outer_ring_6=2;//[1:20]
radius_of_outer_ring_6=18;//[1:100]
y_shift_of_outer_ring_6=0;//[-100:100]
symmetries_of_outer_ring_6=1;//[1:36]
twist_percent_for_outer_ring_6=0;
inner_rings_rotate_with_outer_ring_7="no";//[no,yes]
thickness_of_outer_ring_7=2;//[1:20]
radius_of_outer_ring_7=18;//[1:100]
y_shift_of_outer_ring_7=0;//[-100:100]
symmetries_of_outer_ring_7=1;//[1:36]
twist_percent_for_outer_ring_7=0;
inner_rings_rotate_with_outer_ring_8="no";//[no,yes]
thickness_of_outer_ring_8=2;//[1:20]
radius_of_outer_ring_8=18;//[1:100]
y_shift_of_outer_ring_8=0;//[-100:100]
symmetries_of_outer_ring_8=1;//[1:36]
twist_percent_for_outer_ring_8=0;
inner_rings_rotate_with_outer_ring_9="no";//[no,yes]
thickness_of_outer_ring_9=2;//[1:20]
radius_of_outer_ring_9=18;//[1:100]
y_shift_of_outer_ring_9=0;//[-100:100]
symmetries_of_outer_ring_9=1;//[1:36]
twist_percent_for_outer_ring_9=0;
inner_rings_rotate_with_outer_ring_10="no";//[no,yes]
thickness_of_outer_ring_10=2;//[1:20]
radius_of_outer_ring_10=18;//[1:100]
y_shift_of_outer_ring_10=0;//[-100:100]
symmetries_of_outer_ring_10=1;//[1:36]
twist_percent_for_outer_ring_10=0;
inner_rings_rotate_with_outer_ring_11="no";//[no,yes]
thickness_of_outer_ring_11=2;//[1:20]
radius_of_outer_ring_11=18;//[1:100]
y_shift_of_outer_ring_11=0;//[-100:100]
symmetries_of_outer_ring_11=1;//[1:36]
twist_percent_for_outer_ring_11=0;
inner_rings_rotate_with_outer_ring_12="no";//[no,yes]
thickness_of_outer_ring_12=2;//[1:20]
radius_of_outer_ring_12=18;//[1:100]
y_shift_of_outer_ring_12=0;//[-100:100]
symmetries_of_outer_ring_12=1;//[1:36]
twist_percent_for_outer_ring_12=0;
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 1]*/
number_of_inner_ring_layers_in_ring_1=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_1_layer_1=5;
thickness_of_inner_rings_in_ring_1_layer_1=1;
y_shift_of_inner_rings_in_ring_1_layer_1=0;
symmetries_of_inner_rings_in_ring_1_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_2=5;
thickness_of_inner_rings_in_ring_1_layer_2=1;
y_shift_of_inner_rings_in_ring_1_layer_2=0;
symmetries_of_inner_rings_in_ring_1_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_3=5;
thickness_of_inner_rings_in_ring_1_layer_3=1;
y_shift_of_inner_rings_in_ring_1_layer_3=0;
symmetries_of_inner_rings_in_ring_1_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_4=5;
thickness_of_inner_rings_in_ring_1_layer_4=1;
y_shift_of_inner_rings_in_ring_1_layer_4=0;
symmetries_of_inner_rings_in_ring_1_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_5=5;
thickness_of_inner_rings_in_ring_1_layer_5=1;
y_shift_of_inner_rings_in_ring_1_layer_5=0;
symmetries_of_inner_rings_in_ring_1_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_6=5;
thickness_of_inner_rings_in_ring_1_layer_6=1;
y_shift_of_inner_rings_in_ring_1_layer_6=0;
symmetries_of_inner_rings_in_ring_1_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_7=5;
thickness_of_inner_rings_in_ring_1_layer_7=1;
y_shift_of_inner_rings_in_ring_1_layer_7=0;
symmetries_of_inner_rings_in_ring_1_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_8=5;
thickness_of_inner_rings_in_ring_1_layer_8=1;
y_shift_of_inner_rings_in_ring_1_layer_8=0;
symmetries_of_inner_rings_in_ring_1_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_9=5;
thickness_of_inner_rings_in_ring_1_layer_9=1;
y_shift_of_inner_rings_in_ring_1_layer_9=0;
symmetries_of_inner_rings_in_ring_1_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_1_layer_10=5;
thickness_of_inner_rings_in_ring_1_layer_10=1;
y_shift_of_inner_rings_in_ring_1_layer_10=0;
symmetries_of_inner_rings_in_ring_1_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_1_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 2]*/
number_of_inner_ring_layers_in_ring_2=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_2_layer_1=5;
thickness_of_inner_rings_in_ring_2_layer_1=1;
y_shift_of_inner_rings_in_ring_2_layer_1=0;
symmetries_of_inner_rings_in_ring_2_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_2=5;
thickness_of_inner_rings_in_ring_2_layer_2=1;
y_shift_of_inner_rings_in_ring_2_layer_2=0;
symmetries_of_inner_rings_in_ring_2_layer_2=4;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_3=5;
thickness_of_inner_rings_in_ring_2_layer_3=1;
y_shift_of_inner_rings_in_ring_2_layer_3=0;
symmetries_of_inner_rings_in_ring_2_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_4=5;
thickness_of_inner_rings_in_ring_2_layer_4=1;
y_shift_of_inner_rings_in_ring_2_layer_4=0;
symmetries_of_inner_rings_in_ring_2_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_5=5;
thickness_of_inner_rings_in_ring_2_layer_5=1;
y_shift_of_inner_rings_in_ring_2_layer_5=0;
symmetries_of_inner_rings_in_ring_2_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_6=5;
thickness_of_inner_rings_in_ring_2_layer_6=1;
y_shift_of_inner_rings_in_ring_2_layer_6=0;
symmetries_of_inner_rings_in_ring_2_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_7=5;
thickness_of_inner_rings_in_ring_2_layer_7=1;
y_shift_of_inner_rings_in_ring_2_layer_7=0;
symmetries_of_inner_rings_in_ring_2_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_8=5;
thickness_of_inner_rings_in_ring_2_layer_8=1;
y_shift_of_inner_rings_in_ring_2_layer_8=0;
symmetries_of_inner_rings_in_ring_2_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_9=5;
thickness_of_inner_rings_in_ring_2_layer_9=1;
y_shift_of_inner_rings_in_ring_2_layer_9=0;
symmetries_of_inner_rings_in_ring_2_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_2_layer_10=5;
thickness_of_inner_rings_in_ring_2_layer_10=1;
y_shift_of_inner_rings_in_ring_2_layer_10=0;
symmetries_of_inner_rings_in_ring_2_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_2_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 3]*/
number_of_inner_ring_layers_in_ring_3=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_3_layer_1=5;
thickness_of_inner_rings_in_ring_3_layer_1=1;
y_shift_of_inner_rings_in_ring_3_layer_1=0;
symmetries_of_inner_rings_in_ring_3_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_2=5;
thickness_of_inner_rings_in_ring_3_layer_2=1;
y_shift_of_inner_rings_in_ring_3_layer_2=0;
symmetries_of_inner_rings_in_ring_3_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_3=5;
thickness_of_inner_rings_in_ring_3_layer_3=1;
y_shift_of_inner_rings_in_ring_3_layer_3=0;
symmetries_of_inner_rings_in_ring_3_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_4=5;
thickness_of_inner_rings_in_ring_3_layer_4=1;
y_shift_of_inner_rings_in_ring_3_layer_4=0;
symmetries_of_inner_rings_in_ring_3_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_5=5;
thickness_of_inner_rings_in_ring_3_layer_5=1;
y_shift_of_inner_rings_in_ring_3_layer_5=0;
symmetries_of_inner_rings_in_ring_3_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_6=5;
thickness_of_inner_rings_in_ring_3_layer_6=1;
y_shift_of_inner_rings_in_ring_3_layer_6=0;
symmetries_of_inner_rings_in_ring_3_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_7=5;
thickness_of_inner_rings_in_ring_3_layer_7=1;
y_shift_of_inner_rings_in_ring_3_layer_7=0;
symmetries_of_inner_rings_in_ring_3_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_8=5;
thickness_of_inner_rings_in_ring_3_layer_8=1;
y_shift_of_inner_rings_in_ring_3_layer_8=0;
symmetries_of_inner_rings_in_ring_3_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_9=5;
thickness_of_inner_rings_in_ring_3_layer_9=1;
y_shift_of_inner_rings_in_ring_3_layer_9=0;
symmetries_of_inner_rings_in_ring_3_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_3_layer_10=5;
thickness_of_inner_rings_in_ring_3_layer_10=1;
y_shift_of_inner_rings_in_ring_3_layer_10=0;
symmetries_of_inner_rings_in_ring_3_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_3_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 4]*/
number_of_inner_ring_layers_in_ring_4=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_4_layer_1=5;
thickness_of_inner_rings_in_ring_4_layer_1=1;
y_shift_of_inner_rings_in_ring_4_layer_1=0;
symmetries_of_inner_rings_in_ring_4_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_2=5;
thickness_of_inner_rings_in_ring_4_layer_2=1;
y_shift_of_inner_rings_in_ring_4_layer_2=0;
symmetries_of_inner_rings_in_ring_4_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_3=5;
thickness_of_inner_rings_in_ring_4_layer_3=1;
y_shift_of_inner_rings_in_ring_4_layer_3=0;
symmetries_of_inner_rings_in_ring_4_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_4=5;
thickness_of_inner_rings_in_ring_4_layer_4=1;
y_shift_of_inner_rings_in_ring_4_layer_4=0;
symmetries_of_inner_rings_in_ring_4_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_5=5;
thickness_of_inner_rings_in_ring_4_layer_5=1;
y_shift_of_inner_rings_in_ring_4_layer_5=0;
symmetries_of_inner_rings_in_ring_4_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_6=5;
thickness_of_inner_rings_in_ring_4_layer_6=1;
y_shift_of_inner_rings_in_ring_4_layer_6=0;
symmetries_of_inner_rings_in_ring_4_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_7=5;
thickness_of_inner_rings_in_ring_4_layer_7=1;
y_shift_of_inner_rings_in_ring_4_layer_7=0;
symmetries_of_inner_rings_in_ring_4_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_8=5;
thickness_of_inner_rings_in_ring_4_layer_8=1;
y_shift_of_inner_rings_in_ring_4_layer_8=0;
symmetries_of_inner_rings_in_ring_4_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_9=5;
thickness_of_inner_rings_in_ring_4_layer_9=1;
y_shift_of_inner_rings_in_ring_4_layer_9=0;
symmetries_of_inner_rings_in_ring_4_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_4_layer_10=5;
thickness_of_inner_rings_in_ring_4_layer_10=1;
y_shift_of_inner_rings_in_ring_4_layer_10=0;
symmetries_of_inner_rings_in_ring_4_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_4_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 5]*/
number_of_inner_ring_layers_in_ring_5=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_5_layer_1=5;
thickness_of_inner_rings_in_ring_5_layer_1=1;
y_shift_of_inner_rings_in_ring_5_layer_1=0;
symmetries_of_inner_rings_in_ring_5_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_2=5;
thickness_of_inner_rings_in_ring_5_layer_2=1;
y_shift_of_inner_rings_in_ring_5_layer_2=0;
symmetries_of_inner_rings_in_ring_5_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_3=5;
thickness_of_inner_rings_in_ring_5_layer_3=1;
y_shift_of_inner_rings_in_ring_5_layer_3=0;
symmetries_of_inner_rings_in_ring_5_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_4=5;
thickness_of_inner_rings_in_ring_5_layer_4=1;
y_shift_of_inner_rings_in_ring_5_layer_4=0;
symmetries_of_inner_rings_in_ring_5_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_5=5;
thickness_of_inner_rings_in_ring_5_layer_5=1;
y_shift_of_inner_rings_in_ring_5_layer_5=0;
symmetries_of_inner_rings_in_ring_5_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_6=5;
thickness_of_inner_rings_in_ring_5_layer_6=1;
y_shift_of_inner_rings_in_ring_5_layer_6=0;
symmetries_of_inner_rings_in_ring_5_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_7=5;
thickness_of_inner_rings_in_ring_5_layer_7=1;
y_shift_of_inner_rings_in_ring_5_layer_7=0;
symmetries_of_inner_rings_in_ring_5_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_8=5;
thickness_of_inner_rings_in_ring_5_layer_8=1;
y_shift_of_inner_rings_in_ring_5_layer_8=0;
symmetries_of_inner_rings_in_ring_5_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_9=5;
thickness_of_inner_rings_in_ring_5_layer_9=1;
y_shift_of_inner_rings_in_ring_5_layer_9=0;
symmetries_of_inner_rings_in_ring_5_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_5_layer_10=5;
thickness_of_inner_rings_in_ring_5_layer_10=1;
y_shift_of_inner_rings_in_ring_5_layer_10=0;
symmetries_of_inner_rings_in_ring_5_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_5_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 6]*/
number_of_inner_ring_layers_in_ring_6=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_6_layer_1=5;
thickness_of_inner_rings_in_ring_6_layer_1=1;
y_shift_of_inner_rings_in_ring_6_layer_1=0;
symmetries_of_inner_rings_in_ring_6_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_2=5;
thickness_of_inner_rings_in_ring_6_layer_2=1;
y_shift_of_inner_rings_in_ring_6_layer_2=0;
symmetries_of_inner_rings_in_ring_6_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_3=5;
thickness_of_inner_rings_in_ring_6_layer_3=1;
y_shift_of_inner_rings_in_ring_6_layer_3=0;
symmetries_of_inner_rings_in_ring_6_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_4=5;
thickness_of_inner_rings_in_ring_6_layer_4=1;
y_shift_of_inner_rings_in_ring_6_layer_4=0;
symmetries_of_inner_rings_in_ring_6_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_5=5;
thickness_of_inner_rings_in_ring_6_layer_5=1;
y_shift_of_inner_rings_in_ring_6_layer_5=0;
symmetries_of_inner_rings_in_ring_6_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_6=5;
thickness_of_inner_rings_in_ring_6_layer_6=1;
y_shift_of_inner_rings_in_ring_6_layer_6=0;
symmetries_of_inner_rings_in_ring_6_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_7=5;
thickness_of_inner_rings_in_ring_6_layer_7=1;
y_shift_of_inner_rings_in_ring_6_layer_7=0;
symmetries_of_inner_rings_in_ring_6_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_8=5;
thickness_of_inner_rings_in_ring_6_layer_8=1;
y_shift_of_inner_rings_in_ring_6_layer_8=0;
symmetries_of_inner_rings_in_ring_6_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_9=5;
thickness_of_inner_rings_in_ring_6_layer_9=1;
y_shift_of_inner_rings_in_ring_6_layer_9=0;
symmetries_of_inner_rings_in_ring_6_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_6_layer_10=5;
thickness_of_inner_rings_in_ring_6_layer_10=1;
y_shift_of_inner_rings_in_ring_6_layer_10=0;
symmetries_of_inner_rings_in_ring_6_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_6_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 7]*/
number_of_inner_ring_layers_in_ring_7=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_7_layer_1=5;
thickness_of_inner_rings_in_ring_7_layer_1=1;
y_shift_of_inner_rings_in_ring_7_layer_1=0;
symmetries_of_inner_rings_in_ring_7_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_2=5;
thickness_of_inner_rings_in_ring_7_layer_2=1;
y_shift_of_inner_rings_in_ring_7_layer_2=0;
symmetries_of_inner_rings_in_ring_7_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_3=5;
thickness_of_inner_rings_in_ring_7_layer_3=1;
y_shift_of_inner_rings_in_ring_7_layer_3=0;
symmetries_of_inner_rings_in_ring_7_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_4=5;
thickness_of_inner_rings_in_ring_7_layer_4=1;
y_shift_of_inner_rings_in_ring_7_layer_4=0;
symmetries_of_inner_rings_in_ring_7_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_5=5;
thickness_of_inner_rings_in_ring_7_layer_5=1;
y_shift_of_inner_rings_in_ring_7_layer_5=0;
symmetries_of_inner_rings_in_ring_7_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_6=5;
thickness_of_inner_rings_in_ring_7_layer_6=1;
y_shift_of_inner_rings_in_ring_7_layer_6=0;
symmetries_of_inner_rings_in_ring_7_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_7=5;
thickness_of_inner_rings_in_ring_7_layer_7=1;
y_shift_of_inner_rings_in_ring_7_layer_7=0;
symmetries_of_inner_rings_in_ring_7_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_8=5;
thickness_of_inner_rings_in_ring_7_layer_8=1;
y_shift_of_inner_rings_in_ring_7_layer_8=0;
symmetries_of_inner_rings_in_ring_7_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_9=5;
thickness_of_inner_rings_in_ring_7_layer_9=1;
y_shift_of_inner_rings_in_ring_7_layer_9=0;
symmetries_of_inner_rings_in_ring_7_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_7_layer_10=5;
thickness_of_inner_rings_in_ring_7_layer_10=1;
y_shift_of_inner_rings_in_ring_7_layer_10=0;
symmetries_of_inner_rings_in_ring_7_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_7_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 8]*/
number_of_inner_ring_layers_in_ring_8=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_8_layer_1=5;
thickness_of_inner_rings_in_ring_8_layer_1=1;
y_shift_of_inner_rings_in_ring_8_layer_1=0;
symmetries_of_inner_rings_in_ring_8_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_2=1.5;
thickness_of_inner_rings_in_ring_8_layer_2=1;
y_shift_of_inner_rings_in_ring_8_layer_2=2.5;
symmetries_of_inner_rings_in_ring_8_layer_2=5;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_3=2;
thickness_of_inner_rings_in_ring_8_layer_3=1;
y_shift_of_inner_rings_in_ring_8_layer_3=6;
symmetries_of_inner_rings_in_ring_8_layer_3=5;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_4=2.5;
thickness_of_inner_rings_in_ring_8_layer_4=1;
y_shift_of_inner_rings_in_ring_8_layer_4=10.5;
symmetries_of_inner_rings_in_ring_8_layer_4=5;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_5=3;
thickness_of_inner_rings_in_ring_8_layer_5=1;
y_shift_of_inner_rings_in_ring_8_layer_5=16;
symmetries_of_inner_rings_in_ring_8_layer_5=5;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_6=4.5;
thickness_of_inner_rings_in_ring_8_layer_6=1;
y_shift_of_inner_rings_in_ring_8_layer_6=8.5;
symmetries_of_inner_rings_in_ring_8_layer_6=5;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_7=5;
thickness_of_inner_rings_in_ring_8_layer_7=1;
y_shift_of_inner_rings_in_ring_8_layer_7=0;
symmetries_of_inner_rings_in_ring_8_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_8=5;
thickness_of_inner_rings_in_ring_8_layer_8=1;
y_shift_of_inner_rings_in_ring_8_layer_8=0;
symmetries_of_inner_rings_in_ring_8_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_9=5;
thickness_of_inner_rings_in_ring_8_layer_9=1;
y_shift_of_inner_rings_in_ring_8_layer_9=0;
symmetries_of_inner_rings_in_ring_8_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_8_layer_10=5;
thickness_of_inner_rings_in_ring_8_layer_10=1;
y_shift_of_inner_rings_in_ring_8_layer_10=0;
symmetries_of_inner_rings_in_ring_8_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_8_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 9]*/
number_of_inner_ring_layers_in_ring_9=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_9_layer_1=5;
thickness_of_inner_rings_in_ring_9_layer_1=1;
y_shift_of_inner_rings_in_ring_9_layer_1=0;
symmetries_of_inner_rings_in_ring_9_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_2=5;
thickness_of_inner_rings_in_ring_9_layer_2=1;
y_shift_of_inner_rings_in_ring_9_layer_2=0;
symmetries_of_inner_rings_in_ring_9_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_3=5;
thickness_of_inner_rings_in_ring_9_layer_3=1;
y_shift_of_inner_rings_in_ring_9_layer_3=0;
symmetries_of_inner_rings_in_ring_9_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_4=5;
thickness_of_inner_rings_in_ring_9_layer_4=1;
y_shift_of_inner_rings_in_ring_9_layer_4=0;
symmetries_of_inner_rings_in_ring_9_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_5=5;
thickness_of_inner_rings_in_ring_9_layer_5=1;
y_shift_of_inner_rings_in_ring_9_layer_5=0;
symmetries_of_inner_rings_in_ring_9_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_6=5;
thickness_of_inner_rings_in_ring_9_layer_6=1;
y_shift_of_inner_rings_in_ring_9_layer_6=0;
symmetries_of_inner_rings_in_ring_9_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_7=5;
thickness_of_inner_rings_in_ring_9_layer_7=1;
y_shift_of_inner_rings_in_ring_9_layer_7=0;
symmetries_of_inner_rings_in_ring_9_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_8=5;
thickness_of_inner_rings_in_ring_9_layer_8=1;
y_shift_of_inner_rings_in_ring_9_layer_8=0;
symmetries_of_inner_rings_in_ring_9_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_9=5;
thickness_of_inner_rings_in_ring_9_layer_9=1;
y_shift_of_inner_rings_in_ring_9_layer_9=0;
symmetries_of_inner_rings_in_ring_9_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_9_layer_10=5;
thickness_of_inner_rings_in_ring_9_layer_10=1;
y_shift_of_inner_rings_in_ring_9_layer_10=0;
symmetries_of_inner_rings_in_ring_9_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_9_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 10]*/
number_of_inner_ring_layers_in_ring_10=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_10_layer_1=5;
thickness_of_inner_rings_in_ring_10_layer_1=1;
y_shift_of_inner_rings_in_ring_10_layer_1=0;
symmetries_of_inner_rings_in_ring_10_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_2=5;
thickness_of_inner_rings_in_ring_10_layer_2=1;
y_shift_of_inner_rings_in_ring_10_layer_2=0;
symmetries_of_inner_rings_in_ring_10_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_3=5;
thickness_of_inner_rings_in_ring_10_layer_3=1;
y_shift_of_inner_rings_in_ring_10_layer_3=0;
symmetries_of_inner_rings_in_ring_10_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_4=5;
thickness_of_inner_rings_in_ring_10_layer_4=1;
y_shift_of_inner_rings_in_ring_10_layer_4=0;
symmetries_of_inner_rings_in_ring_10_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_5=5;
thickness_of_inner_rings_in_ring_10_layer_5=1;
y_shift_of_inner_rings_in_ring_10_layer_5=0;
symmetries_of_inner_rings_in_ring_10_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_6=5;
thickness_of_inner_rings_in_ring_10_layer_6=1;
y_shift_of_inner_rings_in_ring_10_layer_6=0;
symmetries_of_inner_rings_in_ring_10_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_7=5;
thickness_of_inner_rings_in_ring_10_layer_7=1;
y_shift_of_inner_rings_in_ring_10_layer_7=0;
symmetries_of_inner_rings_in_ring_10_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_8=5;
thickness_of_inner_rings_in_ring_10_layer_8=1;
y_shift_of_inner_rings_in_ring_10_layer_8=0;
symmetries_of_inner_rings_in_ring_10_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_9=5;
thickness_of_inner_rings_in_ring_10_layer_9=1;
y_shift_of_inner_rings_in_ring_10_layer_9=0;
symmetries_of_inner_rings_in_ring_10_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_10_layer_10=5;
thickness_of_inner_rings_in_ring_10_layer_10=1;
y_shift_of_inner_rings_in_ring_10_layer_10=0;
symmetries_of_inner_rings_in_ring_10_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_10_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 11]*/
number_of_inner_ring_layers_in_ring_11=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_11_layer_1=5;
thickness_of_inner_rings_in_ring_11_layer_1=1;
y_shift_of_inner_rings_in_ring_11_layer_1=0;
symmetries_of_inner_rings_in_ring_11_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_2=5;
thickness_of_inner_rings_in_ring_11_layer_2=1;
y_shift_of_inner_rings_in_ring_11_layer_2=0;
symmetries_of_inner_rings_in_ring_11_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_3=5;
thickness_of_inner_rings_in_ring_11_layer_3=1;
y_shift_of_inner_rings_in_ring_11_layer_3=0;
symmetries_of_inner_rings_in_ring_11_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_4=5;
thickness_of_inner_rings_in_ring_11_layer_4=1;
y_shift_of_inner_rings_in_ring_11_layer_4=0;
symmetries_of_inner_rings_in_ring_11_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_5=5;
thickness_of_inner_rings_in_ring_11_layer_5=1;
y_shift_of_inner_rings_in_ring_11_layer_5=0;
symmetries_of_inner_rings_in_ring_11_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_6=5;
thickness_of_inner_rings_in_ring_11_layer_6=1;
y_shift_of_inner_rings_in_ring_11_layer_6=0;
symmetries_of_inner_rings_in_ring_11_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_7=5;
thickness_of_inner_rings_in_ring_11_layer_7=1;
y_shift_of_inner_rings_in_ring_11_layer_7=0;
symmetries_of_inner_rings_in_ring_11_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_8=5;
thickness_of_inner_rings_in_ring_11_layer_8=1;
y_shift_of_inner_rings_in_ring_11_layer_8=0;
symmetries_of_inner_rings_in_ring_11_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_9=5;
thickness_of_inner_rings_in_ring_11_layer_9=1;
y_shift_of_inner_rings_in_ring_11_layer_9=0;
symmetries_of_inner_rings_in_ring_11_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_11_layer_10=5;
thickness_of_inner_rings_in_ring_11_layer_10=1;
y_shift_of_inner_rings_in_ring_11_layer_10=0;
symmetries_of_inner_rings_in_ring_11_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_11_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[Outer Ring 12]*/
number_of_inner_ring_layers_in_ring_12=1;//[1,2,3,4,5,6,7,8,9,10]
radius_of_inner_rings_in_ring_12_layer_1=5;
thickness_of_inner_rings_in_ring_12_layer_1=1;
y_shift_of_inner_rings_in_ring_12_layer_1=0;
symmetries_of_inner_rings_in_ring_12_layer_1=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_1=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_2=5;
thickness_of_inner_rings_in_ring_12_layer_2=1;
y_shift_of_inner_rings_in_ring_12_layer_2=0;
symmetries_of_inner_rings_in_ring_12_layer_2=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_2=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_3=5;
thickness_of_inner_rings_in_ring_12_layer_3=1;
y_shift_of_inner_rings_in_ring_12_layer_3=0;
symmetries_of_inner_rings_in_ring_12_layer_3=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_3=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_4=5;
thickness_of_inner_rings_in_ring_12_layer_4=1;
y_shift_of_inner_rings_in_ring_12_layer_4=0;
symmetries_of_inner_rings_in_ring_12_layer_4=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_4=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_5=5;
thickness_of_inner_rings_in_ring_12_layer_5=1;
y_shift_of_inner_rings_in_ring_12_layer_5=0;
symmetries_of_inner_rings_in_ring_12_layer_5=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_5=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_6=5;
thickness_of_inner_rings_in_ring_12_layer_6=1;
y_shift_of_inner_rings_in_ring_12_layer_6=0;
symmetries_of_inner_rings_in_ring_12_layer_6=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_6=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_7=5;
thickness_of_inner_rings_in_ring_12_layer_7=1;
y_shift_of_inner_rings_in_ring_12_layer_7=0;
symmetries_of_inner_rings_in_ring_12_layer_7=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_7=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_8=5;
thickness_of_inner_rings_in_ring_12_layer_8=1;
y_shift_of_inner_rings_in_ring_12_layer_8=0;
symmetries_of_inner_rings_in_ring_12_layer_8=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_8=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_9=5;
thickness_of_inner_rings_in_ring_12_layer_9=1;
y_shift_of_inner_rings_in_ring_12_layer_9=0;
symmetries_of_inner_rings_in_ring_12_layer_9=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_9=0;//[1:100]
radius_of_inner_rings_in_ring_12_layer_10=5;
thickness_of_inner_rings_in_ring_12_layer_10=1;
y_shift_of_inner_rings_in_ring_12_layer_10=0;
symmetries_of_inner_rings_in_ring_12_layer_10=1;//[1:36]
twist_percent_of_inner_rings_in_ring_12_layer_10=0;//[1:100]
/////////////////////////////////////////////////////////////////////////////////////////////
/*[hidden]*/
radius_of_inner_rings_in_ring_1=[radius_of_inner_rings_in_ring_1_layer_1,radius_of_inner_rings_in_ring_1_layer_2,radius_of_inner_rings_in_ring_1_layer_3,radius_of_inner_rings_in_ring_1_layer_4,radius_of_inner_rings_in_ring_1_layer_5,radius_of_inner_rings_in_ring_1_layer_6,radius_of_inner_rings_in_ring_1_layer_7,radius_of_inner_rings_in_ring_1_layer_8,radius_of_inner_rings_in_ring_1_layer_9,radius_of_inner_rings_in_ring_1_layer_10];
radius_of_inner_rings_in_ring_2=[radius_of_inner_rings_in_ring_2_layer_1,radius_of_inner_rings_in_ring_2_layer_2,radius_of_inner_rings_in_ring_2_layer_3,radius_of_inner_rings_in_ring_2_layer_4,radius_of_inner_rings_in_ring_2_layer_5,radius_of_inner_rings_in_ring_2_layer_6,radius_of_inner_rings_in_ring_2_layer_7,radius_of_inner_rings_in_ring_2_layer_8,radius_of_inner_rings_in_ring_2_layer_9,radius_of_inner_rings_in_ring_2_layer_10];
radius_of_inner_rings_in_ring_3=[radius_of_inner_rings_in_ring_3_layer_1,radius_of_inner_rings_in_ring_3_layer_2,radius_of_inner_rings_in_ring_3_layer_3,radius_of_inner_rings_in_ring_3_layer_4,radius_of_inner_rings_in_ring_3_layer_5,radius_of_inner_rings_in_ring_3_layer_6,radius_of_inner_rings_in_ring_3_layer_7,radius_of_inner_rings_in_ring_3_layer_8,radius_of_inner_rings_in_ring_3_layer_9,radius_of_inner_rings_in_ring_3_layer_10];
radius_of_inner_rings_in_ring_4=[radius_of_inner_rings_in_ring_4_layer_1,radius_of_inner_rings_in_ring_4_layer_2,radius_of_inner_rings_in_ring_4_layer_3,radius_of_inner_rings_in_ring_4_layer_4,radius_of_inner_rings_in_ring_4_layer_5,radius_of_inner_rings_in_ring_4_layer_6,radius_of_inner_rings_in_ring_4_layer_7,radius_of_inner_rings_in_ring_4_layer_8,radius_of_inner_rings_in_ring_4_layer_9,radius_of_inner_rings_in_ring_4_layer_10];
radius_of_inner_rings_in_ring_5=[radius_of_inner_rings_in_ring_5_layer_1,radius_of_inner_rings_in_ring_5_layer_2,radius_of_inner_rings_in_ring_5_layer_3,radius_of_inner_rings_in_ring_5_layer_4,radius_of_inner_rings_in_ring_5_layer_5,radius_of_inner_rings_in_ring_5_layer_6,radius_of_inner_rings_in_ring_5_layer_7,radius_of_inner_rings_in_ring_5_layer_8,radius_of_inner_rings_in_ring_5_layer_9,radius_of_inner_rings_in_ring_5_layer_10];
radius_of_inner_rings_in_ring_6=[radius_of_inner_rings_in_ring_6_layer_1,radius_of_inner_rings_in_ring_6_layer_2,radius_of_inner_rings_in_ring_6_layer_3,radius_of_inner_rings_in_ring_6_layer_4,radius_of_inner_rings_in_ring_6_layer_5,radius_of_inner_rings_in_ring_6_layer_6,radius_of_inner_rings_in_ring_6_layer_7,radius_of_inner_rings_in_ring_6_layer_8,radius_of_inner_rings_in_ring_6_layer_9,radius_of_inner_rings_in_ring_6_layer_10];
radius_of_inner_rings_in_ring_7=[radius_of_inner_rings_in_ring_7_layer_1,radius_of_inner_rings_in_ring_7_layer_2,radius_of_inner_rings_in_ring_7_layer_3,radius_of_inner_rings_in_ring_7_layer_4,radius_of_inner_rings_in_ring_7_layer_5,radius_of_inner_rings_in_ring_7_layer_6,radius_of_inner_rings_in_ring_7_layer_7,radius_of_inner_rings_in_ring_7_layer_8,radius_of_inner_rings_in_ring_7_layer_9,radius_of_inner_rings_in_ring_7_layer_10];
radius_of_inner_rings_in_ring_8=[radius_of_inner_rings_in_ring_8_layer_1,radius_of_inner_rings_in_ring_8_layer_2,radius_of_inner_rings_in_ring_8_layer_3,radius_of_inner_rings_in_ring_8_layer_4,radius_of_inner_rings_in_ring_8_layer_5,radius_of_inner_rings_in_ring_8_layer_6,radius_of_inner_rings_in_ring_8_layer_7,radius_of_inner_rings_in_ring_8_layer_8,radius_of_inner_rings_in_ring_8_layer_9,radius_of_inner_rings_in_ring_8_layer_10];
radius_of_inner_rings_in_ring_9=[radius_of_inner_rings_in_ring_9_layer_1,radius_of_inner_rings_in_ring_9_layer_2,radius_of_inner_rings_in_ring_9_layer_3,radius_of_inner_rings_in_ring_9_layer_4,radius_of_inner_rings_in_ring_9_layer_5,radius_of_inner_rings_in_ring_9_layer_6,radius_of_inner_rings_in_ring_9_layer_7,radius_of_inner_rings_in_ring_9_layer_8,radius_of_inner_rings_in_ring_9_layer_9,radius_of_inner_rings_in_ring_9_layer_10];
radius_of_inner_rings_in_ring_10=[radius_of_inner_rings_in_ring_10_layer_1,radius_of_inner_rings_in_ring_10_layer_2,radius_of_inner_rings_in_ring_10_layer_3,radius_of_inner_rings_in_ring_10_layer_4,radius_of_inner_rings_in_ring_10_layer_5,radius_of_inner_rings_in_ring_10_layer_6,radius_of_inner_rings_in_ring_10_layer_7,radius_of_inner_rings_in_ring_10_layer_8,radius_of_inner_rings_in_ring_10_layer_9,radius_of_inner_rings_in_ring_10_layer_10];
radius_of_inner_rings_in_ring_11=[radius_of_inner_rings_in_ring_11_layer_1,radius_of_inner_rings_in_ring_11_layer_2,radius_of_inner_rings_in_ring_11_layer_3,radius_of_inner_rings_in_ring_11_layer_4,radius_of_inner_rings_in_ring_11_layer_5,radius_of_inner_rings_in_ring_11_layer_6,radius_of_inner_rings_in_ring_11_layer_7,radius_of_inner_rings_in_ring_11_layer_8,radius_of_inner_rings_in_ring_11_layer_9,radius_of_inner_rings_in_ring_11_layer_10];
radius_of_inner_rings_in_ring_12=[radius_of_inner_rings_in_ring_12_layer_1,radius_of_inner_rings_in_ring_12_layer_2,radius_of_inner_rings_in_ring_12_layer_3,radius_of_inner_rings_in_ring_12_layer_4,radius_of_inner_rings_in_ring_12_layer_5,radius_of_inner_rings_in_ring_12_layer_6,radius_of_inner_rings_in_ring_12_layer_7,radius_of_inner_rings_in_ring_12_layer_8,radius_of_inner_rings_in_ring_12_layer_9,radius_of_inner_rings_in_ring_12_layer_10];
thickness_of_inner_rings_in_ring_1=[thickness_of_inner_rings_in_ring_1_layer_1,thickness_of_inner_rings_in_ring_1_layer_2,thickness_of_inner_rings_in_ring_1_layer_3,thickness_of_inner_rings_in_ring_1_layer_4,thickness_of_inner_rings_in_ring_1_layer_5,thickness_of_inner_rings_in_ring_1_layer_6,thickness_of_inner_rings_in_ring_1_layer_7,thickness_of_inner_rings_in_ring_1_layer_8,thickness_of_inner_rings_in_ring_1_layer_9,thickness_of_inner_rings_in_ring_1_layer_10];
thickness_of_inner_rings_in_ring_2=[thickness_of_inner_rings_in_ring_2_layer_1,thickness_of_inner_rings_in_ring_2_layer_2,thickness_of_inner_rings_in_ring_2_layer_3,thickness_of_inner_rings_in_ring_2_layer_4,thickness_of_inner_rings_in_ring_2_layer_5,thickness_of_inner_rings_in_ring_2_layer_6,thickness_of_inner_rings_in_ring_2_layer_7,thickness_of_inner_rings_in_ring_2_layer_8,thickness_of_inner_rings_in_ring_2_layer_9,thickness_of_inner_rings_in_ring_2_layer_10];
thickness_of_inner_rings_in_ring_3=[thickness_of_inner_rings_in_ring_3_layer_1,thickness_of_inner_rings_in_ring_3_layer_2,thickness_of_inner_rings_in_ring_3_layer_3,thickness_of_inner_rings_in_ring_3_layer_4,thickness_of_inner_rings_in_ring_3_layer_5,thickness_of_inner_rings_in_ring_3_layer_6,thickness_of_inner_rings_in_ring_3_layer_7,thickness_of_inner_rings_in_ring_3_layer_8,thickness_of_inner_rings_in_ring_3_layer_9,thickness_of_inner_rings_in_ring_3_layer_10];
thickness_of_inner_rings_in_ring_4=[thickness_of_inner_rings_in_ring_4_layer_1,thickness_of_inner_rings_in_ring_4_layer_2,thickness_of_inner_rings_in_ring_4_layer_3,thickness_of_inner_rings_in_ring_4_layer_4,thickness_of_inner_rings_in_ring_4_layer_5,thickness_of_inner_rings_in_ring_4_layer_6,thickness_of_inner_rings_in_ring_4_layer_7,thickness_of_inner_rings_in_ring_4_layer_8,thickness_of_inner_rings_in_ring_4_layer_9,thickness_of_inner_rings_in_ring_4_layer_10];
thickness_of_inner_rings_in_ring_5=[thickness_of_inner_rings_in_ring_5_layer_1,thickness_of_inner_rings_in_ring_5_layer_2,thickness_of_inner_rings_in_ring_5_layer_3,thickness_of_inner_rings_in_ring_5_layer_4,thickness_of_inner_rings_in_ring_5_layer_5,thickness_of_inner_rings_in_ring_5_layer_6,thickness_of_inner_rings_in_ring_5_layer_7,thickness_of_inner_rings_in_ring_5_layer_8,thickness_of_inner_rings_in_ring_5_layer_9,thickness_of_inner_rings_in_ring_5_layer_10];
thickness_of_inner_rings_in_ring_6=[thickness_of_inner_rings_in_ring_6_layer_1,thickness_of_inner_rings_in_ring_6_layer_2,thickness_of_inner_rings_in_ring_6_layer_3,thickness_of_inner_rings_in_ring_6_layer_4,thickness_of_inner_rings_in_ring_6_layer_5,thickness_of_inner_rings_in_ring_6_layer_6,thickness_of_inner_rings_in_ring_6_layer_7,thickness_of_inner_rings_in_ring_6_layer_8,thickness_of_inner_rings_in_ring_6_layer_9,thickness_of_inner_rings_in_ring_6_layer_10];
thickness_of_inner_rings_in_ring_7=[thickness_of_inner_rings_in_ring_7_layer_1,thickness_of_inner_rings_in_ring_7_layer_2,thickness_of_inner_rings_in_ring_7_layer_3,thickness_of_inner_rings_in_ring_7_layer_4,thickness_of_inner_rings_in_ring_7_layer_5,thickness_of_inner_rings_in_ring_7_layer_6,thickness_of_inner_rings_in_ring_7_layer_7,thickness_of_inner_rings_in_ring_7_layer_8,thickness_of_inner_rings_in_ring_7_layer_9,thickness_of_inner_rings_in_ring_7_layer_10];
thickness_of_inner_rings_in_ring_8=[thickness_of_inner_rings_in_ring_8_layer_1,thickness_of_inner_rings_in_ring_8_layer_2,thickness_of_inner_rings_in_ring_8_layer_3,thickness_of_inner_rings_in_ring_8_layer_4,thickness_of_inner_rings_in_ring_8_layer_5,thickness_of_inner_rings_in_ring_8_layer_6,thickness_of_inner_rings_in_ring_8_layer_7,thickness_of_inner_rings_in_ring_8_layer_8,thickness_of_inner_rings_in_ring_8_layer_9,thickness_of_inner_rings_in_ring_8_layer_10];
thickness_of_inner_rings_in_ring_9=[thickness_of_inner_rings_in_ring_9_layer_1,thickness_of_inner_rings_in_ring_9_layer_2,thickness_of_inner_rings_in_ring_9_layer_3,thickness_of_inner_rings_in_ring_9_layer_4,thickness_of_inner_rings_in_ring_9_layer_5,thickness_of_inner_rings_in_ring_9_layer_6,thickness_of_inner_rings_in_ring_9_layer_7,thickness_of_inner_rings_in_ring_9_layer_8,thickness_of_inner_rings_in_ring_9_layer_9,thickness_of_inner_rings_in_ring_9_layer_10];
thickness_of_inner_rings_in_ring_10=[thickness_of_inner_rings_in_ring_10_layer_1,thickness_of_inner_rings_in_ring_10_layer_2,thickness_of_inner_rings_in_ring_10_layer_3,thickness_of_inner_rings_in_ring_10_layer_4,thickness_of_inner_rings_in_ring_10_layer_5,thickness_of_inner_rings_in_ring_10_layer_6,thickness_of_inner_rings_in_ring_10_layer_7,thickness_of_inner_rings_in_ring_10_layer_8,thickness_of_inner_rings_in_ring_10_layer_9,thickness_of_inner_rings_in_ring_10_layer_10];
thickness_of_inner_rings_in_ring_11=[thickness_of_inner_rings_in_ring_11_layer_1,thickness_of_inner_rings_in_ring_11_layer_2,thickness_of_inner_rings_in_ring_11_layer_3,thickness_of_inner_rings_in_ring_11_layer_4,thickness_of_inner_rings_in_ring_11_layer_5,thickness_of_inner_rings_in_ring_11_layer_6,thickness_of_inner_rings_in_ring_11_layer_7,thickness_of_inner_rings_in_ring_11_layer_8,thickness_of_inner_rings_in_ring_11_layer_9,thickness_of_inner_rings_in_ring_11_layer_10];
thickness_of_inner_rings_in_ring_12=[thickness_of_inner_rings_in_ring_12_layer_1,thickness_of_inner_rings_in_ring_12_layer_2,thickness_of_inner_rings_in_ring_12_layer_3,thickness_of_inner_rings_in_ring_12_layer_4,thickness_of_inner_rings_in_ring_12_layer_5,thickness_of_inner_rings_in_ring_12_layer_6,thickness_of_inner_rings_in_ring_12_layer_7,thickness_of_inner_rings_in_ring_12_layer_8,thickness_of_inner_rings_in_ring_12_layer_9,thickness_of_inner_rings_in_ring_12_layer_10];
y_shift_of_inner_rings_in_ring_1=[y_shift_of_inner_rings_in_ring_1_layer_1,y_shift_of_inner_rings_in_ring_1_layer_2,y_shift_of_inner_rings_in_ring_1_layer_3,y_shift_of_inner_rings_in_ring_1_layer_4,y_shift_of_inner_rings_in_ring_1_layer_5,y_shift_of_inner_rings_in_ring_1_layer_6,y_shift_of_inner_rings_in_ring_1_layer_7,y_shift_of_inner_rings_in_ring_1_layer_8,y_shift_of_inner_rings_in_ring_1_layer_9,y_shift_of_inner_rings_in_ring_1_layer_10];
y_shift_of_inner_rings_in_ring_2=[y_shift_of_inner_rings_in_ring_2_layer_1,y_shift_of_inner_rings_in_ring_2_layer_2,y_shift_of_inner_rings_in_ring_2_layer_3,y_shift_of_inner_rings_in_ring_2_layer_4,y_shift_of_inner_rings_in_ring_2_layer_5,y_shift_of_inner_rings_in_ring_2_layer_6,y_shift_of_inner_rings_in_ring_2_layer_7,y_shift_of_inner_rings_in_ring_2_layer_8,y_shift_of_inner_rings_in_ring_2_layer_9,y_shift_of_inner_rings_in_ring_2_layer_10];
y_shift_of_inner_rings_in_ring_3=[y_shift_of_inner_rings_in_ring_3_layer_1,y_shift_of_inner_rings_in_ring_3_layer_2,y_shift_of_inner_rings_in_ring_3_layer_3,y_shift_of_inner_rings_in_ring_3_layer_4,y_shift_of_inner_rings_in_ring_3_layer_5,y_shift_of_inner_rings_in_ring_3_layer_6,y_shift_of_inner_rings_in_ring_3_layer_7,y_shift_of_inner_rings_in_ring_3_layer_8,y_shift_of_inner_rings_in_ring_3_layer_9,y_shift_of_inner_rings_in_ring_3_layer_10];
y_shift_of_inner_rings_in_ring_4=[y_shift_of_inner_rings_in_ring_4_layer_1,y_shift_of_inner_rings_in_ring_4_layer_2,y_shift_of_inner_rings_in_ring_4_layer_3,y_shift_of_inner_rings_in_ring_4_layer_4,y_shift_of_inner_rings_in_ring_4_layer_5,y_shift_of_inner_rings_in_ring_4_layer_6,y_shift_of_inner_rings_in_ring_4_layer_7,y_shift_of_inner_rings_in_ring_4_layer_8,y_shift_of_inner_rings_in_ring_4_layer_9,y_shift_of_inner_rings_in_ring_4_layer_10];
y_shift_of_inner_rings_in_ring_5=[y_shift_of_inner_rings_in_ring_5_layer_1,y_shift_of_inner_rings_in_ring_5_layer_2,y_shift_of_inner_rings_in_ring_5_layer_3,y_shift_of_inner_rings_in_ring_5_layer_4,y_shift_of_inner_rings_in_ring_5_layer_5,y_shift_of_inner_rings_in_ring_5_layer_6,y_shift_of_inner_rings_in_ring_5_layer_7,y_shift_of_inner_rings_in_ring_5_layer_8,y_shift_of_inner_rings_in_ring_5_layer_9,y_shift_of_inner_rings_in_ring_5_layer_10];
y_shift_of_inner_rings_in_ring_6=[y_shift_of_inner_rings_in_ring_6_layer_1,y_shift_of_inner_rings_in_ring_6_layer_2,y_shift_of_inner_rings_in_ring_6_layer_3,y_shift_of_inner_rings_in_ring_6_layer_4,y_shift_of_inner_rings_in_ring_6_layer_5,y_shift_of_inner_rings_in_ring_6_layer_6,y_shift_of_inner_rings_in_ring_6_layer_7,y_shift_of_inner_rings_in_ring_6_layer_8,y_shift_of_inner_rings_in_ring_6_layer_9,y_shift_of_inner_rings_in_ring_6_layer_10];
y_shift_of_inner_rings_in_ring_7=[y_shift_of_inner_rings_in_ring_7_layer_1,y_shift_of_inner_rings_in_ring_7_layer_2,y_shift_of_inner_rings_in_ring_7_layer_3,y_shift_of_inner_rings_in_ring_7_layer_4,y_shift_of_inner_rings_in_ring_7_layer_5,y_shift_of_inner_rings_in_ring_7_layer_6,y_shift_of_inner_rings_in_ring_7_layer_7,y_shift_of_inner_rings_in_ring_7_layer_8,y_shift_of_inner_rings_in_ring_7_layer_9,y_shift_of_inner_rings_in_ring_7_layer_10];
y_shift_of_inner_rings_in_ring_8=[y_shift_of_inner_rings_in_ring_8_layer_1,y_shift_of_inner_rings_in_ring_8_layer_2,y_shift_of_inner_rings_in_ring_8_layer_3,y_shift_of_inner_rings_in_ring_8_layer_4,y_shift_of_inner_rings_in_ring_8_layer_5,y_shift_of_inner_rings_in_ring_8_layer_6,y_shift_of_inner_rings_in_ring_8_layer_7,y_shift_of_inner_rings_in_ring_8_layer_8,y_shift_of_inner_rings_in_ring_8_layer_9,y_shift_of_inner_rings_in_ring_8_layer_10];
y_shift_of_inner_rings_in_ring_9=[y_shift_of_inner_rings_in_ring_9_layer_1,y_shift_of_inner_rings_in_ring_9_layer_2,y_shift_of_inner_rings_in_ring_9_layer_3,y_shift_of_inner_rings_in_ring_9_layer_4,y_shift_of_inner_rings_in_ring_9_layer_5,y_shift_of_inner_rings_in_ring_9_layer_6,y_shift_of_inner_rings_in_ring_9_layer_7,y_shift_of_inner_rings_in_ring_9_layer_8,y_shift_of_inner_rings_in_ring_9_layer_9,y_shift_of_inner_rings_in_ring_9_layer_10];
y_shift_of_inner_rings_in_ring_10=[y_shift_of_inner_rings_in_ring_10_layer_1,y_shift_of_inner_rings_in_ring_10_layer_2,y_shift_of_inner_rings_in_ring_10_layer_3,y_shift_of_inner_rings_in_ring_10_layer_4,y_shift_of_inner_rings_in_ring_10_layer_5,y_shift_of_inner_rings_in_ring_10_layer_6,y_shift_of_inner_rings_in_ring_10_layer_7,y_shift_of_inner_rings_in_ring_10_layer_8,y_shift_of_inner_rings_in_ring_10_layer_9,y_shift_of_inner_rings_in_ring_10_layer_10];
y_shift_of_inner_rings_in_ring_11=[y_shift_of_inner_rings_in_ring_11_layer_1,y_shift_of_inner_rings_in_ring_11_layer_2,y_shift_of_inner_rings_in_ring_11_layer_3,y_shift_of_inner_rings_in_ring_11_layer_4,y_shift_of_inner_rings_in_ring_11_layer_5,y_shift_of_inner_rings_in_ring_11_layer_6,y_shift_of_inner_rings_in_ring_11_layer_7,y_shift_of_inner_rings_in_ring_11_layer_8,y_shift_of_inner_rings_in_ring_11_layer_9,y_shift_of_inner_rings_in_ring_11_layer_10];
y_shift_of_inner_rings_in_ring_12=[y_shift_of_inner_rings_in_ring_12_layer_1,y_shift_of_inner_rings_in_ring_12_layer_2,y_shift_of_inner_rings_in_ring_12_layer_3,y_shift_of_inner_rings_in_ring_12_layer_4,y_shift_of_inner_rings_in_ring_12_layer_5,y_shift_of_inner_rings_in_ring_12_layer_6,y_shift_of_inner_rings_in_ring_12_layer_7,y_shift_of_inner_rings_in_ring_12_layer_8,y_shift_of_inner_rings_in_ring_12_layer_9,y_shift_of_inner_rings_in_ring_12_layer_10];
symmetries_of_inner_rings_in_ring_1=[symmetries_of_inner_rings_in_ring_1_layer_1,symmetries_of_inner_rings_in_ring_1_layer_2,symmetries_of_inner_rings_in_ring_1_layer_3,symmetries_of_inner_rings_in_ring_1_layer_4,symmetries_of_inner_rings_in_ring_1_layer_5,symmetries_of_inner_rings_in_ring_1_layer_6,symmetries_of_inner_rings_in_ring_1_layer_7,symmetries_of_inner_rings_in_ring_1_layer_8,symmetries_of_inner_rings_in_ring_1_layer_9,symmetries_of_inner_rings_in_ring_1_layer_10];
symmetries_of_inner_rings_in_ring_2=[symmetries_of_inner_rings_in_ring_2_layer_1,symmetries_of_inner_rings_in_ring_2_layer_2,symmetries_of_inner_rings_in_ring_2_layer_3,symmetries_of_inner_rings_in_ring_2_layer_4,symmetries_of_inner_rings_in_ring_2_layer_5,symmetries_of_inner_rings_in_ring_2_layer_6,symmetries_of_inner_rings_in_ring_2_layer_7,symmetries_of_inner_rings_in_ring_2_layer_8,symmetries_of_inner_rings_in_ring_2_layer_9,symmetries_of_inner_rings_in_ring_2_layer_10];
symmetries_of_inner_rings_in_ring_3=[symmetries_of_inner_rings_in_ring_3_layer_1,symmetries_of_inner_rings_in_ring_3_layer_2,symmetries_of_inner_rings_in_ring_3_layer_3,symmetries_of_inner_rings_in_ring_3_layer_4,symmetries_of_inner_rings_in_ring_3_layer_5,symmetries_of_inner_rings_in_ring_3_layer_6,symmetries_of_inner_rings_in_ring_3_layer_7,symmetries_of_inner_rings_in_ring_3_layer_8,symmetries_of_inner_rings_in_ring_3_layer_9,symmetries_of_inner_rings_in_ring_3_layer_10];
symmetries_of_inner_rings_in_ring_4=[symmetries_of_inner_rings_in_ring_4_layer_1,symmetries_of_inner_rings_in_ring_4_layer_2,symmetries_of_inner_rings_in_ring_4_layer_3,symmetries_of_inner_rings_in_ring_4_layer_4,symmetries_of_inner_rings_in_ring_4_layer_5,symmetries_of_inner_rings_in_ring_4_layer_6,symmetries_of_inner_rings_in_ring_4_layer_7,symmetries_of_inner_rings_in_ring_4_layer_8,symmetries_of_inner_rings_in_ring_4_layer_9,symmetries_of_inner_rings_in_ring_4_layer_10];
symmetries_of_inner_rings_in_ring_5=[symmetries_of_inner_rings_in_ring_5_layer_1,symmetries_of_inner_rings_in_ring_5_layer_2,symmetries_of_inner_rings_in_ring_5_layer_3,symmetries_of_inner_rings_in_ring_5_layer_4,symmetries_of_inner_rings_in_ring_5_layer_5,symmetries_of_inner_rings_in_ring_5_layer_6,symmetries_of_inner_rings_in_ring_5_layer_7,symmetries_of_inner_rings_in_ring_5_layer_8,symmetries_of_inner_rings_in_ring_5_layer_9,symmetries_of_inner_rings_in_ring_5_layer_10];
symmetries_of_inner_rings_in_ring_6=[symmetries_of_inner_rings_in_ring_6_layer_1,symmetries_of_inner_rings_in_ring_6_layer_2,symmetries_of_inner_rings_in_ring_6_layer_3,symmetries_of_inner_rings_in_ring_6_layer_4,symmetries_of_inner_rings_in_ring_6_layer_5,symmetries_of_inner_rings_in_ring_6_layer_6,symmetries_of_inner_rings_in_ring_6_layer_7,symmetries_of_inner_rings_in_ring_6_layer_8,symmetries_of_inner_rings_in_ring_6_layer_9,symmetries_of_inner_rings_in_ring_6_layer_10];
symmetries_of_inner_rings_in_ring_7=[symmetries_of_inner_rings_in_ring_7_layer_1,symmetries_of_inner_rings_in_ring_7_layer_2,symmetries_of_inner_rings_in_ring_7_layer_3,symmetries_of_inner_rings_in_ring_7_layer_4,symmetries_of_inner_rings_in_ring_7_layer_5,symmetries_of_inner_rings_in_ring_7_layer_6,symmetries_of_inner_rings_in_ring_7_layer_7,symmetries_of_inner_rings_in_ring_7_layer_8,symmetries_of_inner_rings_in_ring_7_layer_9,symmetries_of_inner_rings_in_ring_7_layer_10];
symmetries_of_inner_rings_in_ring_8=[symmetries_of_inner_rings_in_ring_8_layer_1,symmetries_of_inner_rings_in_ring_8_layer_2,symmetries_of_inner_rings_in_ring_8_layer_3,symmetries_of_inner_rings_in_ring_8_layer_4,symmetries_of_inner_rings_in_ring_8_layer_5,symmetries_of_inner_rings_in_ring_8_layer_6,symmetries_of_inner_rings_in_ring_8_layer_7,symmetries_of_inner_rings_in_ring_8_layer_8,symmetries_of_inner_rings_in_ring_8_layer_9,symmetries_of_inner_rings_in_ring_8_layer_10];
symmetries_of_inner_rings_in_ring_9=[symmetries_of_inner_rings_in_ring_9_layer_1,symmetries_of_inner_rings_in_ring_9_layer_2,symmetries_of_inner_rings_in_ring_9_layer_3,symmetries_of_inner_rings_in_ring_9_layer_4,symmetries_of_inner_rings_in_ring_9_layer_5,symmetries_of_inner_rings_in_ring_9_layer_6,symmetries_of_inner_rings_in_ring_9_layer_7,symmetries_of_inner_rings_in_ring_9_layer_8,symmetries_of_inner_rings_in_ring_9_layer_9,symmetries_of_inner_rings_in_ring_9_layer_10];
symmetries_of_inner_rings_in_ring_10=[symmetries_of_inner_rings_in_ring_10_layer_1,symmetries_of_inner_rings_in_ring_10_layer_2,symmetries_of_inner_rings_in_ring_10_layer_3,symmetries_of_inner_rings_in_ring_10_layer_4,symmetries_of_inner_rings_in_ring_10_layer_5,symmetries_of_inner_rings_in_ring_10_layer_6,symmetries_of_inner_rings_in_ring_10_layer_7,symmetries_of_inner_rings_in_ring_10_layer_8,symmetries_of_inner_rings_in_ring_10_layer_9,symmetries_of_inner_rings_in_ring_10_layer_10];
symmetries_of_inner_rings_in_ring_11=[symmetries_of_inner_rings_in_ring_11_layer_1,symmetries_of_inner_rings_in_ring_11_layer_2,symmetries_of_inner_rings_in_ring_11_layer_3,symmetries_of_inner_rings_in_ring_11_layer_4,symmetries_of_inner_rings_in_ring_11_layer_5,symmetries_of_inner_rings_in_ring_11_layer_6,symmetries_of_inner_rings_in_ring_11_layer_7,symmetries_of_inner_rings_in_ring_11_layer_8,symmetries_of_inner_rings_in_ring_11_layer_9,symmetries_of_inner_rings_in_ring_11_layer_10];
symmetries_of_inner_rings_in_ring_12=[symmetries_of_inner_rings_in_ring_12_layer_1,symmetries_of_inner_rings_in_ring_12_layer_2,symmetries_of_inner_rings_in_ring_12_layer_3,symmetries_of_inner_rings_in_ring_12_layer_4,symmetries_of_inner_rings_in_ring_12_layer_5,symmetries_of_inner_rings_in_ring_12_layer_6,symmetries_of_inner_rings_in_ring_12_layer_7,symmetries_of_inner_rings_in_ring_12_layer_8,symmetries_of_inner_rings_in_ring_12_layer_9,symmetries_of_inner_rings_in_ring_12_layer_10];
twist_percent_of_inner_rings_in_ring_1=[twist_percent_of_inner_rings_in_ring_1_layer_1,twist_percent_of_inner_rings_in_ring_1_layer_2,twist_percent_of_inner_rings_in_ring_1_layer_3,twist_percent_of_inner_rings_in_ring_1_layer_4,twist_percent_of_inner_rings_in_ring_1_layer_5,twist_percent_of_inner_rings_in_ring_1_layer_6,twist_percent_of_inner_rings_in_ring_1_layer_7,twist_percent_of_inner_rings_in_ring_1_layer_8,twist_percent_of_inner_rings_in_ring_1_layer_9,twist_percent_of_inner_rings_in_ring_1_layer_10];
twist_percent_of_inner_rings_in_ring_2=[twist_percent_of_inner_rings_in_ring_2_layer_1,twist_percent_of_inner_rings_in_ring_2_layer_2,twist_percent_of_inner_rings_in_ring_2_layer_3,twist_percent_of_inner_rings_in_ring_2_layer_4,twist_percent_of_inner_rings_in_ring_2_layer_5,twist_percent_of_inner_rings_in_ring_2_layer_6,twist_percent_of_inner_rings_in_ring_2_layer_7,twist_percent_of_inner_rings_in_ring_2_layer_8,twist_percent_of_inner_rings_in_ring_2_layer_9,twist_percent_of_inner_rings_in_ring_2_layer_10];
twist_percent_of_inner_rings_in_ring_3=[twist_percent_of_inner_rings_in_ring_3_layer_1,twist_percent_of_inner_rings_in_ring_3_layer_2,twist_percent_of_inner_rings_in_ring_3_layer_3,twist_percent_of_inner_rings_in_ring_3_layer_4,twist_percent_of_inner_rings_in_ring_3_layer_5,twist_percent_of_inner_rings_in_ring_3_layer_6,twist_percent_of_inner_rings_in_ring_3_layer_7,twist_percent_of_inner_rings_in_ring_3_layer_8,twist_percent_of_inner_rings_in_ring_3_layer_9,twist_percent_of_inner_rings_in_ring_3_layer_10];
twist_percent_of_inner_rings_in_ring_4=[twist_percent_of_inner_rings_in_ring_4_layer_1,twist_percent_of_inner_rings_in_ring_4_layer_2,twist_percent_of_inner_rings_in_ring_4_layer_3,twist_percent_of_inner_rings_in_ring_4_layer_4,twist_percent_of_inner_rings_in_ring_4_layer_5,twist_percent_of_inner_rings_in_ring_4_layer_6,twist_percent_of_inner_rings_in_ring_4_layer_7,twist_percent_of_inner_rings_in_ring_4_layer_8,twist_percent_of_inner_rings_in_ring_4_layer_9,twist_percent_of_inner_rings_in_ring_4_layer_10];
twist_percent_of_inner_rings_in_ring_5=[twist_percent_of_inner_rings_in_ring_5_layer_1,twist_percent_of_inner_rings_in_ring_5_layer_2,twist_percent_of_inner_rings_in_ring_5_layer_3,twist_percent_of_inner_rings_in_ring_5_layer_4,twist_percent_of_inner_rings_in_ring_5_layer_5,twist_percent_of_inner_rings_in_ring_5_layer_6,twist_percent_of_inner_rings_in_ring_5_layer_7,twist_percent_of_inner_rings_in_ring_5_layer_8,twist_percent_of_inner_rings_in_ring_5_layer_9,twist_percent_of_inner_rings_in_ring_5_layer_10];
twist_percent_of_inner_rings_in_ring_6=[twist_percent_of_inner_rings_in_ring_6_layer_1,twist_percent_of_inner_rings_in_ring_6_layer_2,twist_percent_of_inner_rings_in_ring_6_layer_3,twist_percent_of_inner_rings_in_ring_6_layer_4,twist_percent_of_inner_rings_in_ring_6_layer_5,twist_percent_of_inner_rings_in_ring_6_layer_6,twist_percent_of_inner_rings_in_ring_6_layer_7,twist_percent_of_inner_rings_in_ring_6_layer_8,twist_percent_of_inner_rings_in_ring_6_layer_9,twist_percent_of_inner_rings_in_ring_6_layer_10];
twist_percent_of_inner_rings_in_ring_7=[twist_percent_of_inner_rings_in_ring_7_layer_1,twist_percent_of_inner_rings_in_ring_7_layer_2,twist_percent_of_inner_rings_in_ring_7_layer_3,twist_percent_of_inner_rings_in_ring_7_layer_4,twist_percent_of_inner_rings_in_ring_7_layer_5,twist_percent_of_inner_rings_in_ring_7_layer_6,twist_percent_of_inner_rings_in_ring_7_layer_7,twist_percent_of_inner_rings_in_ring_7_layer_8,twist_percent_of_inner_rings_in_ring_7_layer_9,twist_percent_of_inner_rings_in_ring_7_layer_10];
twist_percent_of_inner_rings_in_ring_8=[twist_percent_of_inner_rings_in_ring_8_layer_1,twist_percent_of_inner_rings_in_ring_8_layer_2,twist_percent_of_inner_rings_in_ring_8_layer_3,twist_percent_of_inner_rings_in_ring_8_layer_4,twist_percent_of_inner_rings_in_ring_8_layer_5,twist_percent_of_inner_rings_in_ring_8_layer_6,twist_percent_of_inner_rings_in_ring_8_layer_7,twist_percent_of_inner_rings_in_ring_8_layer_8,twist_percent_of_inner_rings_in_ring_8_layer_9,twist_percent_of_inner_rings_in_ring_8_layer_10];
twist_percent_of_inner_rings_in_ring_9=[twist_percent_of_inner_rings_in_ring_9_layer_1,twist_percent_of_inner_rings_in_ring_9_layer_2,twist_percent_of_inner_rings_in_ring_9_layer_3,twist_percent_of_inner_rings_in_ring_9_layer_4,twist_percent_of_inner_rings_in_ring_9_layer_5,twist_percent_of_inner_rings_in_ring_9_layer_6,twist_percent_of_inner_rings_in_ring_9_layer_7,twist_percent_of_inner_rings_in_ring_9_layer_8,twist_percent_of_inner_rings_in_ring_9_layer_9,twist_percent_of_inner_rings_in_ring_9_layer_10];
twist_percent_of_inner_rings_in_ring_10=[twist_percent_of_inner_rings_in_ring_10_layer_1,twist_percent_of_inner_rings_in_ring_10_layer_2,twist_percent_of_inner_rings_in_ring_10_layer_3,twist_percent_of_inner_rings_in_ring_10_layer_4,twist_percent_of_inner_rings_in_ring_10_layer_5,twist_percent_of_inner_rings_in_ring_10_layer_6,twist_percent_of_inner_rings_in_ring_10_layer_7,twist_percent_of_inner_rings_in_ring_10_layer_8,twist_percent_of_inner_rings_in_ring_10_layer_9,twist_percent_of_inner_rings_in_ring_10_layer_10];
twist_percent_of_inner_rings_in_ring_11=[twist_percent_of_inner_rings_in_ring_11_layer_1,twist_percent_of_inner_rings_in_ring_11_layer_2,twist_percent_of_inner_rings_in_ring_11_layer_3,twist_percent_of_inner_rings_in_ring_11_layer_4,twist_percent_of_inner_rings_in_ring_11_layer_5,twist_percent_of_inner_rings_in_ring_11_layer_6,twist_percent_of_inner_rings_in_ring_11_layer_7,twist_percent_of_inner_rings_in_ring_11_layer_8,twist_percent_of_inner_rings_in_ring_11_layer_9,twist_percent_of_inner_rings_in_ring_11_layer_10];
twist_percent_of_inner_rings_in_ring_12=[twist_percent_of_inner_rings_in_ring_12_layer_1,twist_percent_of_inner_rings_in_ring_12_layer_2,twist_percent_of_inner_rings_in_ring_12_layer_3,twist_percent_of_inner_rings_in_ring_12_layer_4,twist_percent_of_inner_rings_in_ring_12_layer_5,twist_percent_of_inner_rings_in_ring_12_layer_6,twist_percent_of_inner_rings_in_ring_12_layer_7,twist_percent_of_inner_rings_in_ring_12_layer_8,twist_percent_of_inner_rings_in_ring_12_layer_9,twist_percent_of_inner_rings_in_ring_12_layer_10];
inner_ring_twist_percent_main=[twist_percent_of_inner_rings_in_ring_1,twist_percent_of_inner_rings_in_ring_2,twist_percent_of_inner_rings_in_ring_3,twist_percent_of_inner_rings_in_ring_4,twist_percent_of_inner_rings_in_ring_5,twist_percent_of_inner_rings_in_ring_6,twist_percent_of_inner_rings_in_ring_7,twist_percent_of_inner_rings_in_ring_8,twist_percent_of_inner_rings_in_ring_9,twist_percent_of_inner_rings_in_ring_10,twist_percent_of_inner_rings_in_ring_11,twist_percent_of_inner_rings_in_ring_12];
inner_ring_radius_main=[radius_of_inner_rings_in_ring_1,radius_of_inner_rings_in_ring_2,radius_of_inner_rings_in_ring_3,radius_of_inner_rings_in_ring_4,radius_of_inner_rings_in_ring_5,radius_of_inner_rings_in_ring_6,radius_of_inner_rings_in_ring_7,radius_of_inner_rings_in_ring_8,radius_of_inner_rings_in_ring_9,radius_of_inner_rings_in_ring_10,radius_of_inner_rings_in_ring_11,radius_of_inner_rings_in_ring_12];
inner_ring_thickness_main=[thickness_of_inner_rings_in_ring_1,thickness_of_inner_rings_in_ring_2,thickness_of_inner_rings_in_ring_3,thickness_of_inner_rings_in_ring_4,thickness_of_inner_rings_in_ring_5,thickness_of_inner_rings_in_ring_6,thickness_of_inner_rings_in_ring_7,thickness_of_inner_rings_in_ring_8,thickness_of_inner_rings_in_ring_9,thickness_of_inner_rings_in_ring_10,thickness_of_inner_rings_in_ring_11,thickness_of_inner_rings_in_ring_12];
inner_ring_y_shift_rings_main=[y_shift_of_inner_rings_in_ring_1,y_shift_of_inner_rings_in_ring_2,y_shift_of_inner_rings_in_ring_3,y_shift_of_inner_rings_in_ring_4,y_shift_of_inner_rings_in_ring_5,y_shift_of_inner_rings_in_ring_6,y_shift_of_inner_rings_in_ring_7,y_shift_of_inner_rings_in_ring_8,y_shift_of_inner_rings_in_ring_9,y_shift_of_inner_rings_in_ring_10,y_shift_of_inner_rings_in_ring_11,y_shift_of_inner_rings_in_ring_12];
inner_ring_symmetries_main=[symmetries_of_inner_rings_in_ring_1,symmetries_of_inner_rings_in_ring_2,symmetries_of_inner_rings_in_ring_3,symmetries_of_inner_rings_in_ring_4,symmetries_of_inner_rings_in_ring_5,symmetries_of_inner_rings_in_ring_6,symmetries_of_inner_rings_in_ring_7,symmetries_of_inner_rings_in_ring_8,symmetries_of_inner_rings_in_ring_9,symmetries_of_inner_rings_in_ring_10,symmetries_of_inner_rings_in_ring_11,symmetries_of_inner_rings_in_ring_12];
inner_ring_total_main=[number_of_inner_ring_layers_in_ring_1,number_of_inner_ring_layers_in_ring_2,number_of_inner_ring_layers_in_ring_3,number_of_inner_ring_layers_in_ring_4,number_of_inner_ring_layers_in_ring_5,number_of_inner_ring_layers_in_ring_6,number_of_inner_ring_layers_in_ring_7,number_of_inner_ring_layers_in_ring_8,number_of_inner_ring_layers_in_ring_9,number_of_inner_ring_layers_in_ring_10,number_of_inner_ring_layers_in_ring_11,number_of_inner_ring_layers_in_ring_12];
outer_ring_thickness_main=[thickness_of_outer_ring_1,thickness_of_outer_ring_2,thickness_of_outer_ring_3,thickness_of_outer_ring_4,thickness_of_outer_ring_5,thickness_of_outer_ring_6,thickness_of_outer_ring_7,thickness_of_outer_ring_8,thickness_of_outer_ring_9,thickness_of_outer_ring_10,thickness_of_outer_ring_11,thickness_of_outer_ring_12];
outer_ring_radius_main=[radius_of_outer_ring_1,radius_of_outer_ring_2,radius_of_outer_ring_3,radius_of_outer_ring_4,radius_of_outer_ring_5,radius_of_outer_ring_6,radius_of_outer_ring_7,radius_of_outer_ring_8,radius_of_outer_ring_9,radius_of_outer_ring_10,radius_of_outer_ring_11,radius_of_outer_ring_12];
outer_ring_y_shift_main=[y_shift_of_outer_ring_1,y_shift_of_outer_ring_2,y_shift_of_outer_ring_3,y_shift_of_outer_ring_4,y_shift_of_outer_ring_5,y_shift_of_outer_ring_6,y_shift_of_outer_ring_7,y_shift_of_outer_ring_8,y_shift_of_outer_ring_9,y_shift_of_outer_ring_10,y_shift_of_outer_ring_11,y_shift_of_outer_ring_12];
outer_ring_symmetries_main=[symmetries_of_outer_ring_1,symmetries_of_outer_ring_2,symmetries_of_outer_ring_3,symmetries_of_outer_ring_4,symmetries_of_outer_ring_5,symmetries_of_outer_ring_6,symmetries_of_outer_ring_7,symmetries_of_outer_ring_8,symmetries_of_outer_ring_9,symmetries_of_outer_ring_10,symmetries_of_outer_ring_11,symmetries_of_outer_ring_12];
outer_ring_inner_rotation_main=[inner_rings_rotate_with_outer_ring_1,inner_rings_rotate_with_outer_ring_2,inner_rings_rotate_with_outer_ring_3,inner_rings_rotate_with_outer_ring_4,inner_rings_rotate_with_outer_ring_5,inner_rings_rotate_with_outer_ring_6,inner_rings_rotate_with_outer_ring_7,inner_rings_rotate_with_outer_ring_8,inner_rings_rotate_with_outer_ring_9,inner_rings_rotate_with_outer_ring_10,inner_rings_rotate_with_outer_ring_11,inner_rings_rotate_with_outer_ring_12];
outer_ring_twist_percent_main=[twist_percent_for_outer_ring_1,twist_percent_for_outer_ring_2,twist_percent_for_outer_ring_3,twist_percent_for_outer_ring_4,twist_percent_for_outer_ring_5,twist_percent_for_outer_ring_6,twist_percent_for_outer_ring_7,twist_percent_for_outer_ring_8,twist_percent_for_outer_ring_9,twist_percent_for_outer_ring_10,twist_percent_for_outer_ring_11,twist_percent_for_outer_ring_12];
//loophole For Connection
loop_rotate=orientation_of_loop=="horizontal"?0:90;
translate([0,(y_shift_of_outer_ring_1+((radius_of_outer_ring_1)+(front_to_back_of_loop+(thickness_of_loop/2)))),0]){
	rotate([0,loop_rotate,0]){
		scale([1,stretch_amount_for_loop,front_edge_width_of_loop]){
			rotate_extrude(convexity=10,$fn=render_quality){
				translate([front_to_back_of_loop,0,0]){
					circle(r=(thickness_of_loop/2),$fn=render_quality);
				}
			}
		}
	}
}
//Rings
for(z=[0:number_of_outer_rings-1]){
	for(y=[0:outer_ring_symmetries_main[z]-1]){
		rotate([0,0,((y*(360/outer_ring_symmetries_main[z]))-((360/100)/outer_ring_symmetries_main[z]*outer_ring_twist_percent_main[z]))]){
			translate([0,outer_ring_y_shift_main[z],0]){
				rotate_extrude(convexity=10,$fn=render_quality){
					translate([outer_ring_radius_main[z]-(outer_ring_thickness_main[z]/2),0,0]){
						circle(r=(outer_ring_thickness_main[z]/2),$fn=render_quality);
					}
				}
				intersection(){
					cylinder(r=(outer_ring_radius_main[z]-(outer_ring_thickness_main[z]/2)),h=outer_ring_thickness_main[z],center=true,$fn=render_quality);
					for(x=[0:inner_ring_total_main[z]-1]){
						if(outer_ring_inner_rotation_main[z]=="no"){
							for(i=[0:inner_ring_symmetries_main[z][x]]){
								rotate([0,0,(((i*(360/inner_ring_symmetries_main[z][x]))+((360/100)/inner_ring_symmetries_main[z][x]*inner_ring_twist_percent_main[z][x]))-(360+(y*(360/outer_ring_symmetries_main[z]))))]){
									translate([0,inner_ring_y_shift_rings_main[z][x],0]){
										rotate_extrude(convexity=10,$fn=render_quality)translate([inner_ring_radius_main[z][x],0,0]){
											circle(r=(inner_ring_thickness_main[z][x]/2),$fn=render_quality);
										}
									}
								}
							}
						} 
						else {
							if(outer_ring_inner_rotation_main[z]=="yes"){
								for(i=[0:inner_ring_symmetries_main[z][x]]){
									rotate([0,0,i*360/inner_ring_symmetries_main[z][x]]){
										translate([0,inner_ring_y_shift_rings_main[z][x],0]){ 
											rotate_extrude(convexity=10,$fn=render_quality)translate([inner_ring_radius_main[z][x],0,0]){
												circle(r=(inner_ring_thickness_main[z][x]/2),$fn=render_quality);
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}